---
- name: Create LXD container
  hosts: localhost
  become: true
  vars:
    container_name: lab01
    container_image: ubuntu/focal/amd64
    container_user: mac
    container_password: khima

  tasks:
    - name: Create LXD container
      community.general.lxd_container:
        name: "{{ container_name }}"
        state: started
        image_remote: "{{ container_image }}"
        profiles:
          - default
        config:
          user.user-data: |
            #cloud-config
            users:
              - name: "{{ container_user }}"
                passwd: "{{ container_password }}"
                shell: /bin/bash
                sudo: ALL=(ALL) NOPASSWD:ALL
