---
- name: Deploy LXD VM with User
  hosts: 192.168.1.123  # You can specify the target hosts here
  tasks:
    - name: Create a started container
      community.general.lxd_container:
        name: ubuntu-23-04
        ignore_volatile_options: true
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: lxd # if you get a 404, try setting protocol: simplestreams
          alias: ubuntu/lunar/23.04
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 600

    - name: Create user account
      ansible.builtin.user:
        name: myuser
        password: "{{ 'app@$#0023' | password_hash('sha512') }}"
        shell: /bin/bash
        state: present
        
    - name: Add user to sudo group
      ansible.builtin.user:
        name: myuser
        groups: sudo
        append: yes

    - name: Install required software
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - postgresql
        - openssh-server
