---
- hosts: localhost
  connection: local
  tasks:
  - name: Create an Ubuntu container
    lxd_container:
      name: ubuntu-23-04
      state: started
      source:
        type: image
        mode: pull
        server: https://images.linuxcontainers.org/
        protocol: simplestreams
        alias: ubuntu/lunar/amd64
  - name: Create a user in the container
    delegate_to: ubuntu-23-04
    lxc_user:
      name: mac
      password: khima
      groups: sudo
