---
- name: Create an lxd container
  hosts: 192.168.1.123
  tasks:
    - name: Create a container
      community.general.lxd_container:
        name: lab01
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: simplestreams
          alias: ubuntu/lunar
        profiles:
          - default

    - name: Create a custom user
      user:
        name: mac
        password: "{{ 'khima' | password_hash('sha512') }}"
      delegate_to: lab01

    - name: Set up ssh access
      authorized_key:
        user: mac
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      delegate_to: lab01
