---
- name: Deploy LXD VM with User
  hosts: 192.168.1.123
  tasks:
    - name: Create a started container
      community.general.lxd_container:
        name: ubuntu-23-04
        ignore_volatile_options: true
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: simplestreams
          alias: ubuntu/lunar
        profiles:
          - default
        wait_for_ipv4_addresses: true
        timeout: 600

    - name: Wait for container to start
      delegate_to: ubuntu-23-04
      local_action: wait_for
                    host="ubuntu-23-04"
                    port=8443
                    delay=5
                    timeout=60
      become: no

    - name: Create a user in the container
      command: lxc exec ubuntu-23-04 -- adduser mac --disabled-password --gecos ""
      become: no
