---
- name: Create LXD container
  hosts: 192.168.1.123
  become: true
  tasks:
    - name: Create LXD container
      community.general.lxd_container:
        name: "{{ item.name }}"
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: simplestreams
          alias: "{{ item.image }}"
        profiles:
          - default
  
      with_items:
        - { name: container1, image: ubuntu:23.04 }
        - { name: container2, image: ubuntu:23.04 }
